server:
  port: 8089
spring:
  application:
    name: order-service #在eureka server上显示的应用名称
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?useUnicode=true&characterEncoding=utf8
    username: root
    password: 199712Pj.
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 127.0.0.1 #TODO change IP
    username: guest
    password: guest
    virtual-host: /
    template:
      retry: #消息发送到rabbitmq 中失败后重试
        enabled: true
        initial-interval: 10000ms #发送消息失败后的初始重试时间间隔
        max-interval: 30000ms #发送消息失败后的最大时间间隔，超过这个间隔将不再重试
        multiplier: 2 #第一次发送消息失败后重试时间间隔扩大的倍数
      exchange: leyou.cart.exchange #交换机的名称
    publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true #向Eureka注册的是自己的ip，而不是hostname
    ip-address: 127.0.0.1
mybatis:
  type-aliases-package: com.leyou.order.pojo
ly:
  jwt:
    pubKeyPath: /Users/jie.peng/Documents/rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  worker: #生成订单id所用到的
    workerId: 1
    dataCenterId: 1
  pay:
    appID: wx8397f8696b538317 #公众账号ID
    mchID: 1473426802 #商户号
    key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb #生成签名的密钥
    httpConnectTimeoutMs: 1000 #连接超时时间
    httpReadTimeoutMs: 8000 #读取超时时间
    notifyurl: http://8mzvrp.natappfree.cc/notify/pay #内网穿透(公网)的回调地址
