server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB #限制上传文件的大小,默认为1M
      #max-request-size: #一次请求最大的上传大小，默认为10M
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true #向Eureka注册的是自己的ip，而不是hostname
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
    - 127.0.0.1:22122 #TODO change IP
ly:
  upload:
    baseUrl: http://image.leyou.com:8080/ #采用阿里云服务器的80端口需要进行备案，这里直接使用8080端口
    allowTypes:
      - image/jpeg
      - image/png
      - image/bmp

